name: Build & Test

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            6.0.x
      - name: Install TSDumper Dependencies
        working-directory: TSDumper
        run: npm install
      - name: Run TSDumper
        working-directory: TSDumper
        run: npm run dump
      - name: Run TSDumper
        working-directory: TSDumper
        run: npm run dump
      - name: Run CodeGenerator
        working-directory: CodeGenerator
        run: dotnet run --project src/CodeGenerator.csproj ../TSDumper/output ../Interop/src/Generated $RUNNER_TEMP/stats.json
      - name: Package Interop
        working-directory: Interop
        run: dotnet pack --configuration Release
      - name: Build BlazorSample
        working-directory: Interop/test/BlazorSample
        run: dotnet build